fauna/fauna-js

.github/workflows/pr_validate.yml
.gitignore
package.json
yarn.lock

Adding a workflow to run the test suite during PRs
Failing tests are expected as that's the current state even if I run locally. I want to get the workflow merged so we can fix the tests in separate PRs.

GitHub Actions: PR Validate workflow

---

.github/workflows/pr_validate.yml

We have a test to tries a second local port
Add a second `service` to the workflow
Test passes
Fixing the remaining broken tests

GitHub Actions Workflow: second service

---

README.md

Ticket(s): FE-3173
Need to notify users about the current beta status of this driver.
Add note to top of README

Add beta notice to README

---

.github/pull_request_template.md

Ticket(s): FE-3287
When customers submit pull requests to this repo, they must agree to our terms of reuse.
Update PR template to clarify rights.

Add terms to PR template

---

README.md
src/values/date-time.ts

Ticket(s): [FE-3173](https://faunadb.atlassian.net/browse/FE-3173)
Need to update the README for publishing on NPM.
Content has been reordered and reworked. Left some details out that are more in flux (like errors) and details that will be included in the documentation (like the wire protocol).
----
[FE-3173]: https://faunadb.atlassian.net/browse/FE-3173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update the README

---

README.md
package.json

Tweaking the README to sell the `fql` function more.
----

Tweaking the README to sell the `fql` function more

---

concourse/scripts/publish.sh

Copy pasta led us astray
Fix `set` options
Publish will have the right options enabled 
N/A
Tested locally in a busybox container
----

Correct set options

---

package.json

Bump version for release.
Obeying semantic versioning - since we're still pre-beta no need to bump the major version at this time.
N/A
----

0.5.4 - naming changes + changes to undefined handling

---

README.md

We want to provide customers information about early access.
Update README.
Done
Previewed in GH.
----

Updating README for early access

---

concourse/pipeline.yml

We don't run our platform tests in the pipeline.
Add platform tests to pipeline.
What will change as a result of your pull request? Note that sometimes this section is unnecessary because it is self-explanatory based on the solution.
Only ran a `fly validate-pipeline` for now since we're following prior implementation
----

Add tests to pipeline

---

concourse/pipeline.yml

Copy pasta'd something we don't need
Remove it
Pipeline will be happy 
N/A
None
----

Removed task from pipeline

---

package.json

bumped the patch version.
----

Prepare for next patch release

---

__tests__/integration/query.test.ts
package.json
src/client.ts
src/http-client/index.ts
src/util/environment.ts
tsconfig.json
yarn.lock

Ticket(s): [FE-3011](https://faunadb.atlassian.net/browse/FE-3011)
We don't send the driver environment details.
Send them!
Gathers and formats information to send via the `X-Driver-Env` header.
Test added to make sure the header exists.
Integration tests will make sure this works in other environments besides Node.
----
[FE-3011]: https://faunadb.atlassian.net/browse/FE-3011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fingerprinting

---

__tests__/functional/client-configuration.test.ts
src/client.ts

Add some tests and validation for new ClientConfiguration settings.

---

concourse/pipeline.yml

Remove temporary inside joke from pipeline

---

__tests__/integration/schema-version.test.ts

My original test was working locally but I didn't' correctly account for resource management when running in the pipeline.  This should resolve that.

fix schema version test

---

src/client-configuration.ts

Doc comment for `query_timeout_ms` is wrong
Update doc comment
Less confusion
N/A
N/A
----

Updated doc comment

---

concourse/tasks/integration-tests.yml

Using the wrong entrypoint for docker.
Use the right one.
----

Fix entrypoint for docker

---

concourse/tasks/query-limits-tests.yml

Pointing at incorrect path in `testtools` repo
Fix the path
Path is fixed
Other paths?
Stared really hard at it
----

Fix `testtools` pipeline path

---

concourse/pipeline.yml

Fix query limits test

---

concourse/pipeline.yml

Remove cversion check in main

---

concourse/pipeline.yml
concourse/scripts/publish.sh

Explicitly set tag

---

docker/feature-flags.json

Add feature-flag file

---

README.md

Update the installation instructions for beta.
----

Update beta install instructions

---

concourse/scripts/docker-compose-fauna.yml

current faunadb image doesn't include streaming!! 😞 
update faunadb
no other changes.
----

Use latest faunadb image

---

README.md

Updates the streaming examples to align with the new sample data.
----

[DOCS-3455] README: Update streaming sample data
