__tests__/functional/client-configuration.test.ts
__tests__/integration/query.test.ts

Some of the tests are too explicit
- Only assert the `data` on the result
- replace `.not.toBeUndefined()` with `toBeDefined()`
- don't validate `summary` contents, just that it's set 
A few tests pass
Fix remaining tests

Update query test assertions

---

__tests__/integration/query.test.ts

❌ [tests/integration/query.test.ts](https://github.com/fauna/fauna-js/runs/11337521216#r0s3)
query with QueryRequest
❌ throws a QueryCheckError if the query is invalid
Error: expect.assertions(5)
❌ throws a QueryCheckError if the query is invalid
Error: expect.assertions(5)
Fix them
✅

Updated Query tests

---

__tests__/unit/query.test.ts

Something is up with the TypeScript linting where it can't figure out that NetworkError extends Error
```
Property 'cause' does not exist on type 'NetworkError'.
```
- `@ts-ignore` the lines for now
- simplified `expect` while I was there
No "Problems" showing up in my workspace now 🙌

ts-ignore NetworkError instances in tests

---

__tests__/integration/query.test.ts

Updated to the latest nightly docker image and the test started to fail. Test shouldn't assert the `message` contents from core.
Simplify the test assertion
Test validates the driver only

Updated authentication test

---

lib/client-configuration.d.ts
lib/http-client/fetch-client.d.ts
lib/http-client/index.d.ts
src/http-client/fetch-client.ts
src/http-client/index.ts

Ticket(s): [FE-3064](https://faunadb.atlassian.net/browse/FE-3064)
This is an initial milestone to review a generic HTTPClient interface
[FE-3064]: https://faunadb.atlassian.net/browse/FE-3064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FE-3064] Define an HTTPClient interface and default fetch client

---

package.json

Ticket(s): [FE-3079](https://faunadb.atlassian.net/browse/FE-3079)
Can run tests out of the box unless you have access to the private repo
FQLX can be enabled in the public docker image, now, so we can test against that
update the test scripts in package.json
I've been temporarily doing this the whole time and now am finally making a PR for it 😄
[FE-3079]: https://faunadb.atlassian.net/browse/FE-3079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Use public docker image for testing

---

fauna-local-config.yml
package.json

Relates to #68 
FQL X is enabled by default in latest versions of the docker image
Remove the config
Less stuff to worry about

Remove feature flag config

---

__tests__/functional/tagged-format.test.ts
lib/tagged-type.d.ts
lib/values.d.ts
src/tagged-type.ts
src/values.ts

Ticket(s): FE-2979
Latest version of FQL X defaults to tagged type formatting
Implement tagged type formatting encoding/decoding
Can send/received tagged type format
Updating the Client request/response to use `tagged` format

Tagged Type Formatting

---

README.md
__tests__/integration/existing-collection.test.ts
package.json

We have now finalized our collection data format and will begin giving some customers early access to fql x.  This test is going to ensure that we don't make any backwards incompatible changes to our collection data format.  The plan is to run this after the dev and preview deploys in the database pipeline.
We also plan to run the full drivers test suite in these pipelines to ensure we don't have any backwards incompatible drivers changes.  Some of those tests don't currently work when pointed at dev, taking an incremental approach here and will be getting this test in the pipeline first while I work on resolving the other drivers tests.  At that point will switch to running all of the integ tests in the pipeline.

add simple integ test against existing collection

---

__tests__/functional/client-configuration.test.ts
__tests__/integration/client-last-txn-tracking.test.ts
__tests__/unit/query-builder.test.ts
src/client.ts
src/wire-protocol.ts

Ticket(s): [FE-3118](https://faunadb.atlassian.net/browse/FE-3118)
Per stand up, drivers should align on last_txn_ts semantics and remove the option from the request API.
Remove the option from the request API. Setting lastTxnTs through the Client should not throw an Error, but instead take the larger value of lastTxnTs or the user input.
[FE-3118]: https://faunadb.atlassian.net/browse/FE-3118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove last_txn_ts from request API

---

src/client.ts

Ticket(s): [FE-3118](https://faunadb.atlassian.net/browse/FE-3118)
Docs still talked about the Client.lastTxnTs setter as throwing an error, which we just changed.
[FE-3118]: https://faunadb.atlassian.net/browse/FE-3118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix docs for `set lastTxnTs`

---

__tests__/functional/tagged-format.test.ts
src/tagged-type.ts

Ticket(s): [FE-3124](https://faunadb.atlassian.net/browse/FE-3124)
Core will be shipping wire protocol changes and we need to handle these as follows:
Drivers continue to encode per the current protocol. On decode:
- If @doc tag and it’s an object, strip the tag
- If @doc tag and it’s a string, build a doc reference from it
- If @set tag, strip it
- if @ref tag, build a doc reference
The minimal change to decode @doc, @ref and @set to plain js object. We can decode into more complex classes but can do that after the actual protocol changes land.
Once the change is deployed, drivers can update to encode to the new protocol and use @set to build iterators
Added tests for @ref and @set. Updated tests for @doc and added the case where @doc is an object.
[FE-3124]: …

Decode new format for @doc @ref and @set

---

__tests__/unit/tagged-format.test.ts
__tests__/unit/values.test.ts
src/errors.ts
src/regex.ts
src/tagged-type.ts
src/values.ts

Ticket(s): [FE-3080](https://faunadb.atlassian.net/browse/FE-3080)
Fauna's `Time` type can store nanosecond precision. Javascript `Date` can only store milliseconds.
There is no built in type for "plain" dates in JS. Closest thing is using a `Date` with time set to 00:00:00 UTC. So Javascript `Date` is not well suited to store Fauna `Date` values.
Provide our own type, very simple wrappers a la v4 driver. Stores the exact encoded string value. 
Native Javascript `Date`s are always encoded as a Fauna `Time`.
Users may still need JS `Date`s to do date/time things with it, so they may lose precision when converting to and from.
Added a unit tests for constructing and deconstructing FaunaTime and FaunaDate. Updated tests for encoding and decoding.
[FE-3080]: …

Date time wrappers

---

__tests__/integration/query.test.ts
src/errors.ts
src/wire-protocol.ts

Ticket(s): FE-3150
- While fixing dashboard bugs noticed we are not including `constraint_failures` in our wire protocol.
- Same is true across all drivers
- https://github.com/fauna/fauna-go/blob/fqlx-beta/error.go
- https://github.com/fauna/fauna-python/blob/main/fauna/errors.py
- Include optional constraint_failures array on `QueryFailure` wire model
- clients, such as the dashboard, can detect constraint_failures
Verifying tests still pass.

FE-3150 Add constraint_failures to wire protocol.

---

src/errors.ts

Ticket(s): [FE-3076](https://faunadb.atlassian.net/browse/FE-3076)
The error classes don't have a common base class besides `Error`. Per standup discussion, we want to synchronize the drivers by providing a common base class.
Create a new `abstract class FaunaError` with which to derive the other errors.
not affected
[FE-3076]: https://faunadb.atlassian.net/browse/FE-3076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Provide common error base class

---

src/tagged-type.ts
src/wire-protocol.ts

Ticket(s): 
- [FE-3109](https://faunadb.atlassian.net/browse/FE-3109)
- [FE-3178](https://faunadb.atlassian.net/browse/FE-3178)
`TaggedTypeFormat` is a class with only static methods, and `TaggedTypeEncoded` is a type that is not used outside of the module. The methods in these classes can be simplified to regular functions. The functions are still encapsulated within the module.
Refactor the class methods into regular functions. Add a default export to encapsulate the exports into a single object.
updated imports for test files that call the encoding/decoding functions.
[FE-3109]: https://faunadb.atlassian.net/browse/FE-3109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FE-3178]: https://faunadb.atlassian.net/browse/FE-3178?atlOrigin=eyJpIjo …

Remove TaggedTypeEncoded class and fix types

---

__tests__/functional/client-configuration.test.ts
__tests__/integration/query.test.ts
__tests__/unit/query-builder.test.ts
src/client-configuration.ts
src/client.ts
src/wire-protocol.ts

Ticket(s): [FE-3181](https://faunadb.atlassian.net/browse/FE-3181)
We need to expose an option to enable or disable typechecking at the Client and the Query. The default should be that x-typecheck is unset.
- Add an optional `typecheck` field to `ClientConfiguration`
- Add an optional `typecheck` field to `QueryRequestHeaders`
Extended tests to ensure 
- the client configuration sets a header; and 
- query options sets a header and overrides the client configuration
[FE-3181]: https://faunadb.atlassian.net/browse/FE-3181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add typecheck configuration option

---

__tests__/integration/client-last-txn-tracking.test.ts
__tests__/integration/query.test.ts
__tests__/unit/fetch-client.test.ts
src/client.ts
src/wire-protocol.ts

Ticket(s): [FE-3109](https://faunadb.atlassian.net/browse/FE-3109)
In `QueryStats`, `storage_bytes_written` should be `storage_bytes_write`
The fields for `QueryInfo` are incorrectly specified as required/optional.
`QueryInfo.query_tags` is not decoded correctly. It comes back exactly how the header is sent, e.g. 
```
"project=teapot,hello=world,testing=foobar"
```
Align types with the core spec.
Add decoding of `query_tags` if received.
Added new test for `query_tags`.
[FE-3109]: https://faunadb.atlassian.net/browse/FE-3109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix QueryStats and QueryInfo types and tests

---

src/http-client/index.ts
src/values/date-time.ts
src/wire-protocol.ts

Ticket(s): FE-3212
- decorated wire format supports REPLs and CLIs
- we are building a REPL in the dashboard
- include the decorated format
- dashboard can show decorated output on its REPL

Support decorated format. Fix linting errors

---

concourse/scripts/docker-compose-fauna.yml
wait-for-it.sh

- integ tests are failing regularly in pipeline. Suspect this is because we are querying before the Fauna container is started.
- move to a more brute force health check that curls fauna.
- stabler integ tests 🤞 
Ran on docker locally:
```
~/workplace/fauna-js (main_changeFaunaHealthCheck*) » docker-compose -f concourse/scripts/docker-compose-fauna.yml run node-lts                                        1 ↵ cleve@Cleves-MBP
+ ./wait-for-it.sh http://faunadb:8443/ping
...+ yarn test:integration
yarn run v1.22.19
$ yarn install; jest --run-in-band ./__tests__/integration
[1/4] Resolving packages...
success Already up-to-date.
$ husky install
husky - git command not found, skipping install
PASS  __tests__/integration/query.test.ts (8.776 s)
PASS  __tests__/integration/doc.test.ts
PASS …
```

Update health check on integration tests in pipeline to use curl.

---

README.md

- README says you got to clone this repo
- developer setup was first up in README
- point to NPM / yarn
- move developer setup to the bottom
- README is accurate
----

Update README.md to account for NPM

---

__tests__/integration/query.test.ts
__tests__/unit/query.test.ts
src/errors.ts

Ticket(s): [FE-3109](https://faunadb.atlassian.net/browse/FE-3109)
Fauna will possible send any of the QueryInfo fields with a QueryFailure. The corresponding ServiceError class currently only stores the `summary` field.
Replace the `ServiceError.summary` field with a QueryInfo object.
Added a new `ServiceError.queryInfo` field that is the QueryInfo object.
N/A
Updated tests to check for `error.queryInfo.summary` instead of `error.summary`.
----
[FE-3109]: https://faunadb.atlassian.net/browse/FE-3109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Store all QueryInfo fields in ServiceError

---

__tests__/functional/client-configuration.test.ts
src/client-configuration.ts
src/client.ts

* Update the default endpoint to be called default
* Remove preview endpoint
* Update the demo package
yarn test
----

Endpoint as default and remove preview

---

__tests__/functional/client-configuration.test.ts
__tests__/integration/client-last-txn-tracking.test.ts
__tests__/integration/query.test.ts
__tests__/integration/template-format.test.ts
__tests__/unit/query-builder.test.ts
__tests__/unit/query.test.ts
src/client.ts
src/index.ts
src/query-builder.ts
src/wire-protocol.ts

Ticket(s): [FE-3301](https://faunadb.atlassian.net/browse/FE-3301)
We want to push users toward best practice by requiring them to use the `fql` function.
Eliminate the `QueryBuilder` interface. Rename `TemplateQueryBuilder` to `Query`. Check if arguments are also `Query` instances with `instanceof` instead of a predicate function to check for the interface.
Client.query only accepts a `Query` instance.
Removed all tests that specifically intended to exercise passing `QueryRequest` to `Client.query`. Fixed other tests to use `fql` function.
----
[FE-3301]: https://faunadb.atlassian.net/browse/FE-3301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Z …

Client accepts only fql output as input

---

__tests__/functional/client-configuration.test.ts
src/client.ts

Ticket(s): [FE-3293](https://faunadb.atlassian.net/browse/FE-3293)
Providing an endpoint without the trailing slash doesn't work
Use the `URL` API to append `/query/1` to the endpoint.
final URL is the same with or without a trailing slash in the endpoint.
Added new client configuration test.
----
[FE-3293]: https://faunadb.atlassian.net/browse/FE-3293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Client can accept endpoints with or without a trailing Slash

---

package.json

I didn't do a bump such that this is marked breaking since we still haven't gone to private beta. So just incrementing the patch version.
- Need to bump version to release items blocking private beta
- bump version to release items blocking private beta
- can release
- N/A
----

Bump version to release changes to query builder, etc.

---

README.md
__tests__/integration/existing-collection.test.ts
src/index.ts
src/query-builder.ts
src/tagged-type.ts
src/values/doc.ts
src/values/set.ts
src/wire-protocol.ts

Ticket(s): FE-3307
- the wire protocol is no longer restricted to plain JSON
- however, our client-side objects and docs still refer to 'json'
- rename `JSONValue` -> `QueryValue` and `JSONObject` -> `QueryValueObject`
- clean up docs to not refer to 'json' either.
- semantically coherent type names
- fixing up whatever issues sit with this in the demo directory - will handle that in one fell swoop as there's other issues
- full suite (see Github Actions)
- grepped the repo for mentions of jsonvalue and jsonobject (case insensitive)
```
~/workplace/fauna-js (main_renameJSON) » grep -ri jsonobject src/ __tests__ README.md                                                                                  1 ↵ cleve@Cleves-MBP
--------------------------------------------------------------------- …
```

FE-3307 Rename JSONValue -> QueryValue and JSONObject -> QueryValueObject

---

__tests__/integration/query.test.ts
src/tagged-type.ts

Ticket(s): FE-3306
We don't handle undefined values in queries; leading to 400s anytime an undefined value is in user input.
```
QueryRuntimeError: Invalid request body
at Client.#getServiceError (/Users/cleve/workplace/fauna-js/src/client.ts:208:16)
at Client.#getError (/Users/cleve/workplace/fauna-js/src/client.ts:163:37)
at Client.#query (/Users/cleve/workplace/fauna-js/src/client.ts:278:29)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at Object.<anonymous> (/Users/cleve/workplace/fauna-js/__tests__/integration/query.test.ts:309:26) {
httpStatus: 400,
code: 'invalid_request',
queryInfo: {
txn_ts: undefined,
summary: undefined,
query_tags: undefined,
stats: undefined
},
constraint_failures: undefined
}
```
This is a problem because using undefined to denote …

FE-3306 Treat undefined values in QueryValueObject as unprovided. Reject undefined in QueryValue.

---

package.json
src/http-client/index.ts

- the isNode algorithm is still insufficient. Calling "process" leads to a ReferenceError.
- updated algorithm to check the typeof process.
- have confirmed i can run fauna-js in the browser now.
- tested this by setting my local dashboard to depend on my local repo of fauna.
I can now load the views that use FQL X and have also confirmed that this is the source onbox.
I've posted the screenshots to our slack room.
----

Update isNode algorithm to check typeof process to avoid ReferenceError in browser

---

package.json
src/http-client/index.ts
src/http-client/node-http2-client.ts

Ticket(s): FE-3061
- webpack bundled apps cannot use driver as it references the NodeHTTP2Client in an import - despite it being excluded from build
- include the NodeHTTP2Client in all builds
- refactor the NodeHTTP2Client to use `require` to pull in the `node:http2` module
- if an error occurs requiring the `node:http2` module throw an error if a user tries to construct a NodeHTTP2Client
- the JS driver can run on the browser and on the server
```
~/workplace/fauna-js (main_webpackFix) » grep -rl "../src" dist                                                                                                            cleve@Cleves-MBP
dist/browser/index.js.map                
dist/node/index.js.map
-----------------------------------------
```
```
grep -r "NodeHTTP2Client" dist/browser …
```

Include NodeHTTP2Client in browser build - but load node:http2 module in try catch

---

.husky/pre-commit

Pre-commit hook runs yarn even when making changes that don't require it
Only run the `yarn` commands when we make `*.ts` or `package.json` changes
Pre-commit hook is less annoying
Locally validated
----

Update precommit hook

---

__tests__/client.ts
__tests__/functional/client-configuration.test.ts
__tests__/integration/client-last-txn-tracking.test.ts
__tests__/integration/doc.test.ts
__tests__/integration/existing-collection.test.ts
__tests__/integration/page.test.ts
__tests__/integration/query.test.ts
__tests__/integration/template-format.test.ts
__tests__/unit/client.test.ts
__tests__/unit/fetch-client.test.ts
__tests__/unit/query.test.ts
src/client.ts
src/errors.ts
src/http-client/fetch-client.ts
src/http-client/index.ts
src/http-client/node-http2-client.ts

- customers need a way to close their clients
- expose a close method
- for the shared HTTP/2 client in node use reference counting to only close when no more processes are using the global http2 connection.
- close available to users
- full suite
- added tests to show we're tracking references, can recreate on global pool after all are closed.
----

Close with reference counting to protect the global node http2 client

---

__tests__/integration/query.test.ts
src/client-configuration.ts
src/client.ts

Ticket(s): [FE-3396](https://faunadb.atlassian.net/browse/FE-3396)
In order to make sure that we are providing the best driverless-experience, we need to make sure that drivers are setting the format header so that the default can be the most appropriate for direct API access
Make `format` a required client configuration field. Provide a default format.
Since the client configuration will always have a format, the `x-format` header will always be sent
N/A
tweaked the headers test so that it uses the default client configuration for format (i.e. not explicitly set), so we now test the the header is sent by default.
----
[FE-3396]: …

Send x-format header by default

---

__tests__/integration/query.test.ts
src/client.ts
src/errors.ts
src/index.ts

Ticket(s): 
- [FE-3388](https://faunadb.atlassian.net/browse/FE-3388)
- [FE-3402](https://faunadb.atlassian.net/browse/FE-3402)
We should distinguish between 400 errors from invalid reuqests, calling `abort`, and those from other issues, so users can more easily handle them.
We've not added an error for 409 errors yet.
Create a AbortError class and throw it if a 400 error has the code "abort".
Create an InvalidRequestError class and throw it if a 400 error has the code "invalid_request".
Create a ContendedTransactionError class and throw it on a 409 response.
Also included a nit about using `expect.toBe` instead of `expect.toEqual` which is more for asserting the values of objects.
n/a
Core updated the wire protocol, so we can now also test that the code coming back is "abort" and not …

Add AbortError, InvalidRequestError, and ContendedTransactionError classes

---

package.json
src/values/doc.ts

There were a couple errors in the documentation in doc.ts that was using an older FQL X syntax.
Revamp the documentation in this file to fix bugs and make the examples a bit more spelled out.
I also took the liberty of changing "Thing" to "Users" as it feels a bit more concrete.
Documentation is up to date.
N/A
----

Fix some errors in the doc.ts documentation and make the examples a bit easier to read.

---

__tests__/integration/doc.test.ts
__tests__/unit/doc.test.ts
__tests__/unit/tagged-format.test.ts
src/index.ts
src/tagged-type.ts
src/values/doc.ts

Ticket(s): [FE-3211](https://faunadb.atlassian.net/browse/FE-3211)
If a Document cannot be read, Fauna returns a Reference with `exists: false`. We need to handle that case.
Add a `NullDocument` type to decode non-existing refs
Decodes non-existing refs to the new `NullDocument` type. `NullDocument`s are encoded as a reference when passed back to Fauna.
n/a
Added new tests for NullDocument. I also realized that we don't test the encoding/decoding for any of the document types, so added those as well.
----
[FE-3211]: https://faunadb.atlassian.net/browse/FE-3211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …

Support nulldoc

---

__tests__/integration/page.test.ts
__tests__/integration/set.test.ts
__tests__/unit/page.test.ts
__tests__/unit/set.test.ts
__tests__/unit/tagged-format.test.ts
src/client.ts
src/index.ts
src/tagged-type.ts
src/values/index.ts
src/values/page.ts
src/values/set.ts
src/wire-protocol.ts

Ticket(s): [FE-3110](https://faunadb.atlassian.net/browse/FE-3110)
We want to provide native async-iterator API for fetching multiple pages of data.
We want to limit friction for users getting paginated data.
Users need to have control over remote fetches, and need access to the after-cursors if they want them.
Add the `EmbeddedSet` class to differentiate between a materialized Set (Page) and an unmaterialized one. This lets us enforce that a `Page` instance always contains data.
Add a `SetIterator` class. This version of `SetIterator` is different in a couple of ways:
- Instances of `Page` are unwrapped, so results from iterating are always `T[]` instead of `Page<T>`.
- `SetIterator` can be constructed from a nullary function that returns `Promise<QuerySuccess<QueryValue>>`. The first …

Pagination iterator type (3) - Can iterate directly over a query

---

concourse/scripts/publish.sh

- stakeholders want to know when new driver versions are published
- tag them in slack
- folks get notified
- need to do a release and see if we ping OK
----

Notify watchers when driver published

---

__tests__/integration/query.test.ts
__tests__/unit/client.test.ts
src/http-client/index.ts
src/http-client/node-http2-client.ts
src/tagged-type.ts

Ticket(s): FE-3527
- we are creating 1 NodeHTTP2Client per Fauna Client
- we are storing references to NodeHTTP2Client to do ref counting in a set
- can save a few resources with some refactoring
- create 1 NodeHTTP2Client per unique HTTPOptions used to build a NodeHTTP2Client
- do ref counting via a numeric counter
- same behavior for customer
- space saved
- Full test suite. See GitHub actions
----

FE-3527 Optimize NodeHTTP2Client to create one NodeHTTP2Client per HTTPClientOptions

---

concourse/scripts/publish.sh

- stakeholders want to know when driver published.
- the `@` tags don't work over the stripe API. You have to use the group id instead: https://github.com/cloudfoundry-community/slack-notification-resource
- use the group id
- stakeholders get pinged
- need to do a release to test it
----

Ping the watchers on release

---

__tests__/integration/client-last-txn-tracking.test.ts
__tests__/integration/query.test.ts
__tests__/unit/node-http2-client.test.ts
src/client-configuration.ts
src/client.ts
src/http-client/fetch-client.ts
src/http-client/node-http2-client.ts

Ticket(s): FE-3305
- TLDR; In Node, there is a race condition between handling GOAWAY and submitting requests - that can cause clients that safely checked handle go away to submit requests fter a GOAWAWY was recieved anyway.
- A short idle timeout can trigger this race condition.
- We had several tests not closing clients, leaving open handles (items still waiting for events on test exit) - which could mask bugs on close.
- technical explanation: node HTTP2 request gets put on event queue before it is actually executed. In the interim, a GOAWAY can come and cause the request to fail with a GOAWAY.
- retry on GOAWAY up to three times. I did not put a sleep in here as it should be pretty snappy. We just need to get in line properly in the event queue.
- Increase the default idle timeout.
- …

FE-3305 Handle Node HTTP2 race condition on GOAWAY

---

__tests__/integration/query-typings.test.ts

- Customer asking how to deserialize into their own types
- write test case showing how to do this for both `query` and `paginate`
- functionality of using own types will be regression tested
- ran tests
----

Write test to prove customers can use their own types

---

__tests__/integration/query.test.ts

Ticket(s): [FE-3537](https://faunadb.atlassian.net/browse/FE-3537)
The integration test for constraint failures relied on creating a function whose name collided with a built-in function. But Core changed the name of that function so the test now fails.
Try to create the same function twice.
Doesn't matter what the name of the function is now.
passing
----
[FE-3537]: https://faunadb.atlassian.net/browse/FE-3537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Make constraint failure test more robust

---

README.md
__tests__/integration/query.test.ts
src/client-configuration.ts
src/client.ts
src/index.ts
src/query-builder.ts
src/wire-protocol.ts

Ticket(s): [FE-3564](https://faunadb.atlassian.net/browse/FE-3564)
We do not send query options in the request body, so QueryHeaders is not part of the wire protocol. We've already updated Client.query to only accept the `Query` type, so there is no way for users to provide query options through the current `QueryRequest` type.
- `QueryRequest` should not extend `QueryHeaders`
- Rename `QueryHeaders` to `QueryOptions`
- `QueryOptions` should be an optional second argument to query.
- When `QueryOptions` and `ClientConfiguration` make the same setting, `QueryOptions` takes precedence.
- Add an `arguments` field to `QueryOptions` to make up for the fact that we are not passing a `QueryRequest` directly to `Client.query`.
The wire-protocol module sticks to describing the data can is sent and …

Separate QueryOptions from QueryRequest

---

.github/workflows/pr_validate.yml
README.md
concourse/scripts/docker-compose-fauna.yml
concourse/tasks/npm-publish.yml

Ticket(s): FE-3565
v20 is now active
v19 end-of-life is 2023-06-01
v18.16 is also released
Update test images and README supported runtimes
n/a
Ran the [docker-compose-fauna.yml](https://github.com/fauna/fauna-js/blob/main/concourse/scripts/docker-compose-fauna.yml) locally. I got an error initially, but that appears to be transient. It passes in additional runs.
Initial errors, for the record:
```shell
node-current  | [3/4] Linking dependencies...
node-current  | error An unexpected error occurred: "EEXIST: file already exists, symlink '../../../parser/bin/babel-parser.js' -> '/tmp/app/node_modules/@babel/traverse/node_modules/.bin/parser'".
node-current  | info If you think this is a bug, please open a bug report with the information provided in "/tmp/app/yarn-error.log".
node-current …
```

Update Node.js runtime versions

---

README.md
src/errors.ts
src/index.ts

Ticket(s): FE-3541
We need some clarification around timeout configuration options, their relation to each other, related errors, why `Client.close()` should be used, etc.
Update the README
Also fixed the missing export for `FaunaError` since we document using that in the README.
[preview](https://github.com/fauna/fauna-js/blob/af9655bb659f588d424a25d78ef26ca4670e7cf5/README.md)
Adding every option and public function to the README. We should generate tsdocs for that.
n/a
----

Document timeout configuration

---

src/client.ts
src/util/environment.ts

- platform test failures
- are old code was passing our platform tests fine - so go back to using a syntax closer to what we have before
- platform tests 
Testing against Nuxt JS
----

Rework process.env typeguards due to platform test failures

---

src/client.ts
src/util/environment.ts

- cloudflare tests failing
- be more verbose in fallback fauna secret checking
- Nuxt JS supported and Cloudflare support maintained
- Nuxt still works - cloud flare testing will happen in pipeline
----

Be more verboces in process.env checking

---

src/client.ts
src/http-client/index.ts

- in certain engined you get a ReferenceError if you call a variable that has never been declared.
- check typeof process before using it.
- we can run on CloudFlare
- N/A
Testing Nuxt and will test clouflare in Pipeline
----

Check typeof process before you use it

---

README.md

Quickstart invokes a variable that doesn't exist.
Update the quickstart to use the defined variable.
----

docs(readme): fix quickstart variable use

---

README.md

Ticket(s): 
fixes #175
1. The example is supposed to demonstrate arguments through query options, not interpolation.
2. Spaces are not allowed in query tags. Per the API spec, each key and each value may only contain the characters [a-zA-Z0-9_].
Update the example.
Example is now runnable.
n/a
tested examples locally
----

Fix Query Options README example

---

src/util/environment.ts

Ticket(s): [FE-3729](https://faunadb.atlassian.net/browse/FE-3729)
Fixes #173 
Leaving this as a draft while we get some testing done.
We currently assume that if you are not running in Node or Service Worker, you are in a browser. That blows up in environments like Vercel's Edge Runtime and Fastly's Compute@Edge.
Explicitly check for browser env before getting details from `navigator` object. If none of our env checks are true, then report unknown.
Running locally with some edge projects.
----
[FE-3729]: https://faunadb.atlassian.net/browse/FE-3729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Explicitly check for browser env

---

__tests__/integration/schema-version.test.ts
src/wire-protocol.ts

Leaving this as draft for now as the change to add the schema version hasn't made it out to prod yet.
ENG-5237
This builds on a change to core that started including the schema version in the query API response: https://github.com/fauna/core/blob/master/ext/api/src/main/resources/openapi.yml#L393 This schema version can be used by the dashboard to determine when it needs to refresh the schema.  This includes both displaying schema to users as well as refreshing the environment used by the language library to provide intellisense.

add schema version to drivers

---

src/http-client/node-http2-client.ts

ENG-5289
I noticed while working on the vs code extension that if I lose connectivity to core it ends up destroying the session and then it continues to fail even if I regain connectivity. Small change here to also refresh the session if it ended up getting destroyed.
https://nodejs.org/api/http2.html#http2sessiondestroyed

refresh session when destroyed

---

__tests__/client.ts
__tests__/integration/schema-version.test.ts

Adds a test helper we have in the database (`newDB`), which creates a fresh DB for each run.
It then uses this helper to fix the schema version test.

Add test helpers

---

yarn.lock

This reverts commit 484aa440f4032fe059fa29af51a3219f0e96a299.
The commit being reverted broke many tests.
Revert it. Also, turn mandatory test runs back on in the branch protection (commit was merged via auto-merge which did not require a test run).
Tip of main works.
Ran full suite locally. Actions will do the same.
----

Revert "Bump word-wrap from 1.2.3 to 1.2.5 (#190)"

---

.github/workflows/pr_donotmerge.yml

Ticket(s): BT-4101
We don't have a way to tag PRs that block them from being merged.
Add a workflow that blocks when a PR is tagged with `pr/do-not-merge`.
We can safely stage PRs without them being accidentally merged.
None
----

Add Github action the honors the pr/do-not-merge tag

---

__tests__/integration/query.test.ts

Ticket(s): 
Some tests fail when static type-checking is on by default.
Update failing tests.
n/a
run integration tests on env with typechecking on by default
----

Get tests to pass when type checking is on.

---

concourse/tasks/integration-tests.yml

bash is not supported in this entry point script.
use sh
----

Run integ test script in sh not bash

---

concourse/scripts/docker-compose-fauna.yml
concourse/tasks/integration-tests.yml

The pipeline is stuck because we cannot run integration tests successfully due to compatibility issues in the docker images we use inside our CD pipeline.
A temporary work around for this is to pin the fauna db image we use in the CD pipeline to 4.28
We can run the pipeline.
Made this same work around on the pipeline for a private repo and it works as expected.
----

Pin fauna version in pipeline

---

__tests__/functional/client-configuration.test.ts
src/client.ts

Ticket(s): FE-4347
fixes: #205
In the README, it states that the FAUNA_ENDPOINT environment variable can be used to override the default endpoint client configuration setting. However, this is not getting honored when set.
Fall back on the env variable if endpoint is not explicitly set. THEN fall back on the default (https://db.fauna.com).
If the endpoint is explicitly set to `undefined`, then we still throw a TypeError, rather than fall back on any values.
env var is honored.
Added a test.
----

endpoint falls back to FAUNA_ENDPOINT env variable

---

src/client.ts

I'm not sure why we hid this in the first place. The code to construct the client needs to know the secret, and this just lets you avoid passing the secret around alongside the client.

Expose the secret in `client.clientConfiguration`

---

__tests__/unit/client.test.ts
src/client.ts
src/wire-protocol.ts

Ticket(s): FE-4356
This allows overriding the client's secret on a `query` call.
This might screw up `last_txn_ts` if you switch region groups. That should quickly resolve itself, as the last_txn_ts will catch up quickly.

Allow overriding the client's secret

---

README.md
__tests__/unit/fetch-client.test.ts
__tests__/unit/query.test.ts
src/client-configuration.ts
src/client.ts
src/wire-protocol.ts

Ticket(s): FE-2988
We need to retry throttling errors within the client.
* Expose max_attempts and max_backoff in client configuration
* Backoff/retry on throttling error up to max_attempts
* Added unit test
----

Add retries on throttling errors

---

__tests__/integration/query-limits.test.ts
concourse/pipeline.yml
concourse/scripts/docker-compose-fauna.yml
concourse/tasks/query-limits-tests.yml
package.json

Ticket(s): BT-4181
We don't currently have integration test coverage of the query-limit and throttling behavior.
Add a test case that runs against a specially-configured database with query limits and validate that the queries that are throttled succeed on the Client retry logic.
Depends on this PR: https://github.com/fauna/testtools/pull/86
New test case added and running in pipeline.
Ran the test many times locally; will need to validate in the pipeline that the Concourse collateral is setup correctly.
----

BT-4181: Query limits test case and pipeline collateral

---

concourse/tasks/query-limits-tests.yml

Volumes are ephemeral in concourse pipeline, so no need to prune/rm them.
----

No need to `docker volume rm` in pipeline

---

concourse/scripts/docker-compose-fauna-limits.yml
concourse/scripts/docker-compose-fauna.yml
concourse/tasks/query-limits-tests.yml

Integ-tests are blocked by changes to docker-compose-fauna.yml
Split the new test into its own docker-compose
No more blocking of integ-tests
----

Move query limits tests to separate docker-compose file

---

__tests__/integration/query.test.ts
src/client.ts

Ticket(s): FE-4675
Setting args to `undefined` serializes them, causing the database to complain about the string `undefined` in a header.

Fix setting args to undefined adding them to headers

---

src/client.ts

Ticket(s): [FE-4969](https://faunadb.atlassian.net/browse/FE-4969)
Small breaking change, but looking for feedback first. Compared to the callback example in https://github.com/fauna/fauna-js/pull/232, this would remove the concept of registering one or more callbacks before the `start` method. There is no adding or removing of callbacks, and no more no ambiguity about how the async interface should work if you have registered callbacks. Here is a modified example:
```javascript
import { Client, fql } from "fauna"
const client = new Client({ secret: FAUNA_SECRET })
const stream = client.stream(fql`MyCollection.all().toStream()`)
stream.start(
function onEvent(event) {
switch (event.type) {
case "start":
console.log("Stream start", event);
// ...
break;
case "update":
case "add":
case …
```

Provide exactly one handler for events and another for fatal errors

---

src/http-client/node-http2-client.ts

Ticket(s): FE-4969
The first iteration of v10 streaming did provide a default implementation for Node.js
Add a streaming implementation to the `NodeHTTP2Client` class
V10 streams can be used in Node.js by default
There are changes to the error shape on the core side that might not initially be incorporated here.
I am running tests with a Node.js script running locally on my machine.
----

Initial implementation for streams with http2 module

---

concourse/pipeline.yml
concourse/scripts/publish.sh
concourse/tasks/integration-tests.yml
concourse/tasks/npm-publish.yml
concourse/tasks/query-limits-tests.yml

We don't have a workflow that supports releasing beta versions of the driver without merging into main.
Create a beta branch (protected) and extend the pipeline to support releases from that branch.
The pipeline has been set. Internal reviewers can find it.
----

Setup pipeline for beta deploy

---

.github/workflows/pr_validate.yml
README.md
__tests__/functional/stream-client-configuration.test.ts
__tests__/integration/set.test.ts
__tests__/integration/stream.test.ts
concourse/pipeline.yml
concourse/scripts/publish.sh
concourse/tasks/integration-tests.yml
concourse/tasks/npm-publish.yml
concourse/tasks/query-limits-tests.yml
docker/feature-flags.json
package.json
src/client-configuration.ts
src/client.ts
src/errors.ts
src/http-client/fetch-client.ts
src/http-client/http-client.ts
src/http-client/index.ts
src/http-client/node-http2-client.ts
src/index.ts
src/tagged-type.ts
src/values/index.ts
src/values/stream.ts
src/wire-protocol.ts

Ticket(s): FE-4969
This is an initial go at implementing streaming events for the v10 API. Anything here is up for review and comment.
Implement the v10 Fauna streaming API
We need to support browsers and Node. We would also like to support other runtimes if possible.
Provide a `StreamClient` class which provides the primary user interface to establish a stream and handle events.
Provide a lower-level `HTTPStreamClient` interface that can be implemented for different environments.
The `StreamClient` contains an instance of an `HTTPStreamClient`, which mirrors the existing lower-level `HTTPClient` interface that enables different backend implementations for the `Client` class.
The `HTTPStreamClient` is responsible for initiating a request and returning an object that implements the …

Initial Streaming Implementation

---

concourse/pipeline.yml
concourse/scripts/publish.sh

Use repo.git for dir

---

README.md

Ticket(s): [DOCS-2595](https://faunadb.atlassian.net/browse/DOCS-2595)
The current JavaScript driver README introduces concepts in a somewhat confusing order. It also has some minor grammar/styling issues.
- Reorganizes and reorders the README into install, usage, and configuration sections
- Removes the [Connecting from the browser](https://github.com/fauna/fauna-js?tab=readme-ov-file#connecting-from-the-browser) and [Importing into a bundled project](https://github.com/fauna/fauna-js?tab=readme-ov-file#importing-into-a-bundled-project) sections. These are redundant and already covered.
- Adds `console.log(...)` to a few code snippets.
- Makes minor grammar/styling fixes
- Overhauling the client configuration section. We can likely simplify this into a table.
- Documenting all supported …

[DOCS-2595] Reorganize JS driver README

---

package.json
src/tagged-type.ts
yarn.lock

`yarn audit` reports some vulnerabilities. Also, some unnecessary eslint warnings are now fixed.
Update dev dependencies, and run `npx yarn-audit-fix`
Zero vulnerabilities found
```shell
> yarn audit
yarn audit v1.22.21
0 vulnerabilities found - Packages audited: 546
```
Imports that are used in TSDocs are no longer flagged as unused variables.
N/A
Existing tests passing.
----

Update dev dependencies

---

README.md

Ticket(s): [DOCS-2634](https://faunadb.atlassian.net/browse/DOCS-2634)
We don't currently document the `Client.paginate()` method.
Add documentation to the README.
----
[DOCS-2634]: https://faunadb.atlassian.net/browse/DOCS-2634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-2634] Document `Client.paginate()`

---

README.md

Ticket(s): [DOCS-2646](https://faunadb.atlassian.net/browse/DOCS-2646)
The `<stream>.close()` method for Event Streaming is undocumented.
Documents the method.
----
[DOCS-2646]: https://faunadb.atlassian.net/browse/DOCS-2646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-2646] Document `<stream>.close()` method

---

__tests__/integration/query.test.ts
__tests__/integration/stream.test.ts
__tests__/unit/error.test.ts
__tests__/unit/query.test.ts
src/client.ts
src/errors.ts
src/http-client/fetch-client.ts
src/http-client/node-http2-client.ts
src/index.ts

Ticket(s): [FE-5040](https://faunadb.atlassian.net/browse/FE-5040)
`HTTPStreamClient` implementations need to throw service errors if the initial response is a non-200. The logic to convert `QueryFailure` responses to the appropriate sub type is currently a private method on the `Client` class.
The `StreamClient` also needs to throw the appropriate service error class when a type=error event is received.
Move the `Client.#getServiceError` method to the `errors` module so it can be reused. Use it to throw the appropriate error if a type=error event is received or if the initial response is a non-200.
There is no http status code associated with streaming error events, so we should update error handling to rely first on the error code, then fallback to the base `ServiceError` if the error …

Sort service errors into the proper subclass

---

src/client-configuration.ts
src/errors.ts
src/values/date-time.ts
src/values/doc.ts
src/values/set.ts
src/wire-protocol.ts

Ticket(s): [DOCS-2744](https://faunadb.atlassian.net/browse/DOCS-2744)
Links to docs are still using the old FQL beta urls.
Update the links!
N/A
No functional changes.
----
[DOCS-2744]: https://faunadb.atlassian.net/browse/DOCS-2744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-2744] Replace FQLX beta doc links in `beta` branch

---

__tests__/integration/template-format.test.ts
__tests__/unit/tagged-format.test.ts
package.json
src/index.ts
src/query-builder.ts
src/tagged-type.ts
src/wire-protocol.ts
yarn.lock

Ticket(s): [FE-4855](https://faunadb.atlassian.net/browse/BT-4855)
Fauna supports a Bytes type which is transmitted as a base-64-encoded string
https://docs.fauna.com/fauna/current/reference/fql_reference/types#bytes
We also had a type issue where JS Date could not be used as a query argument, so I added Date to arg type as well as a test.
Add encoding and decoding of the Bytes type
`ArrayBuffer`s, `TypedArray`s (e.g. Uint8Array, Int32Array, etc.), as well as Node's `Buffer` classes are encoded to Fauna Bytes.
Fauna Bytes are decoded into `Uint8Array`, which can be used to create the desired type.
See tests for examples.
N/A
Added unit and integration tests for Node. Browser is untested.
----
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

Add encoding/decoding for Fauna Bytes

---

__tests__/unit/error.test.ts
__tests__/unit/query.test.ts
src/errors.ts

The error code for 429 throttling errors is `limit_exceeded`, but we are using `throttle`, an incorrect placeholder from preexisting code.
See canonical list of error codes from core:
https://github.com/fauna/core/blob/395d2a23d83a95c42102d5b9d02d2b49b191720c/ext/api/src/main/scala/api/fql2/FQL2Response.scala#L281
Update the error code.
Correct handling of 429 limit-exceeded errors.
Run query limits tests locally by default: [FE-5412](https://faunadb.atlassian.net/browse/FE-5412)
Concourse pipeline covers tests for exceeding query limits.
I installed the local driver in an App I have that is known to have throughput issues. Before this fix, I incorrectly get `QueryRuntimeError`'s. After this fix, I correctly get `ThrottlingError`'s and automatic retries work.
----
By …

Fix error code for ThrottlingError

---

concourse/scripts/docker-compose-fauna.yml

We updated typescript which is only compatible with Node 18.18 or higher. Current pipeline pulls Node 18.16.
Update node images.
No changes. Should be fine once newer images are provided.
----

update concourse node versions

---

concourse/pipeline.yml

We decided that releasing a beta version is probably overkill.
Remove the beta components of the release pipeline. We'll probably gate beta features behind configuration going forward, but TBD.
None
----

Remove beta release from pipeline

---

README.md

Ticket(s): [DOCS-2817](https://faunadb.atlassian.net/browse/DOCS-2817), [DOCS-2819](https://faunadb.atlassian.net/browse/DOCS-2819)
- Documents the `flatten()` method for pagination
- Removes class names from method references in text. This aligns with Google's [style recommendations](https://developers.google.com/style/code-in-text#method-names). A user was recently confused by it. ([ref](https://github.com/fauna/fauna-js/pull/262#discussion_r1609318063))
----
[DOCS-2817]: https://faunadb.atlassian.net/browse/DOCS-2817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOCS-2819]: …

[DOCS-2817] [DOCS-2819] Document `flatten()` pagination fn

---

__tests__/integration/query-limits.test.ts
__tests__/integration/query.test.ts
__tests__/integration/template-format.test.ts
__tests__/unit/query-builder.test.ts
__tests__/unit/tagged-format.test.ts
src/client.ts
src/query-builder.ts
src/tagged-type.ts
src/wire-protocol.ts

Ticket(s): [FE-3501](https://faunadb.atlassian.net/browse/FE-3501)
`Query` instances (i.e. results from the `fql` function) cannot be encoded when embedded in objects or arrays.
The `QueryValue` type is incorrectly used for types over the wire.
The database now accepts a query interpolation fragments for `array` and `object`, where the existing `fql` fragment can now be nested under the `array` and `object` fragments. Add new `encodeInterpolation` method to encode with the new fragments.
Query `arguments` do not use interpolation, so they still need the `@object` tag. Encoding arguments still uses the existing `encode` method.
Update types to better distinguish between
- Arguments to be encoded
- allow `Query` within objects and arrays
- `QueryValue` should remain a valid `QueryArgument` …

Support users embedding fql snippets in objects and arrays

---

__tests__/integration/query.test.ts
src/wire-protocol.ts

Ticket(s): [FE-5552](https://faunadb.atlassian.net/browse/FE-5552)
The type `ConstraintFailure["paths"]` was set to be `Array<number | string>`. However, the wire response for `paths` is actually an array of arrays. Anyone trying to interact with `paths` using the declared types would have a runtime error. The existing integration tests only check `paths` is defined.
Fix the the types to match the current response, and update the integration tests to actually test the array of array data structure. The `expect` statements were updated to use more "complex" matchers to reduce the number of assertions while visually documenting the data structures.
The types now match the expected wire result and the integration tests validate that structure more concretely.
N/A.
Updated the existing …

Fix incorrect paths type on ConstraintFailure

---

README.md

Ticket(s): [DOCS-3140](https://faunadb.atlassian.net/browse/DOCS-3140)
Query tag values can't contain spaces.
Fixes a bad example in the README.
----
[DOCS-3140]: https://faunadb.atlassian.net/browse/DOCS-3140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-3140] Fix query tag bug is JS driver readme

---

README.md
src/client.ts

Ticket(s): [FE-5389](https://faunadb.atlassian.net/browse/FE-5389)
#277 introduced a typo in a client docstring and new type testing techniques that are not explicitly called out in the README.
* Fix spacing typo
* Add a new "Asserting type behavior" in the "Contributing" section of the readme
----
[FE-5389]: https://faunadb.atlassian.net/browse/FE-5389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update docstring and readme with changes requested in #277

---

__tests__/integration/query-limits.test.ts

The query limit integration tests can sometimes timeout with at 20000. This makes our release pipeline flaky for new versions. 
Increasing the query limit timeout to 30000 should eliminate timeout failures outside of events where dependencies are actually failing.
None. This is a theory with minimal risk/downside.
----

Increase query limit integration test timeout value

---

.gitignore
concourse/pipeline.yml
concourse/scripts/publish_docs.sh
concourse/tasks/publish-docs.yml
overview.md
package-lock.json
package.json
typedoc.json

Ticket(s): [DOCS-3194](https://faunadb.atlassian.net/browse/DOCS-3194)
**IMPORTANT:**
I don't have access to Concourse pipelines so I'll need someone to test those changes for me.
We don't currently publish API reference for the v10 JavaScript/TypeScript driver.
During recent onboarding interviews, some customers have requested these docs.
- Use TypeDoc to generate API reference from TypeScript source and comments.
- Incorporate publication into the Concourse pipeline
- Host the docs on GH pages (via the `gh-pages` branch).
The API docs will be available at https://fauna.github.io/fauna-js/.
I've already backfilled docs for the current release (2.2.0) in the [gh-pages branch](https://github.com/fauna/fauna-js/tree/gh-pages), but I'm holding off on publication until this PR is approved. …

[DOCS-3194] Generate API docs for JS driver

---

README.md
__tests__/integration/stream.test.ts
src/client-configuration.ts
src/client.ts
src/wire-protocol.ts

Provide support for the new per-event stream cursor.
There's an edge case where resuming a stream from a txn time with lots of documents written could result in event loss. This approach fixes that edge case.
Unit tests included.
NA
* - [X] Bug fix (non-breaking change that fixes an issue)
* - [X] New feature (non-breaking change that adds functionality)
* - [X] My code follows the code style of this project.
* - [X] My change requires a change to Fauna documentation.
* - [X] My change requires a change to the README, and I have updated it accordingly.
----

ENG-6606: Introduce event cursor support

---

README.md

- Fixes capitalization for "Event Streaming" in the README
- Updates the link to the `StreamClientConfiguration` type.
----

[DOCS-3435] README: Fix Event Streaming config link

---

__tests__/unit/fetch-client.test.ts
__tests__/unit/node-http2-client.test.ts
src/http-client/fetch-client.ts
src/http-client/http-client.ts
src/http-client/index.ts
src/http-client/node-http2-client.ts
src/http-client/paths.ts

This PR extends the existing `HTTPRequest` to take an optional path to support POST requests to endpoints other than `/query/1`.
We'll need to support requests to Fauna APIs beyond `/query/1`. Today, this API path is hardcoded in both the fetch and http2 client wrappers. This PR does the following:
- Extends `HTTPRequest` to accept an optional `path`
- Updates `FetchClient` to use default API paths, but override per request when one is provided on `HTTPRequest`
- Updates `NodeHTTP2Client` to use default API paths, but override per request when one is provided on `HTTPRequest`
- Adds a readonly `FaunaAPI` to represent the supported API paths in the driver
- Restricts `HTTPRequest["path"]` to the union of supported endpoints via `FaunaAPI`
We need to support more endpoints in this driver. …

Extend HTTPRequest to support path overrides

---

.github/workflows/pr_validate.yml
README.md
concourse/scripts/docker-compose-fauna-limits.yml
concourse/scripts/docker-compose-fauna.yml
concourse/tasks/npm-publish.yml
concourse/tasks/publish-docs.yml

Issues: FE-5636
Update the Node environments in Concourse to latest images for Node v20 and v22.
Node v22 has been current for several months and we should be testing against it.
I can run tests locally using Node v22.
Concourse will be updated and we'll see results before publishing new version.
* - [ ] Bug fix (non-breaking change that fixes an issue)
* - [x] My code follows the code style of this project.
* - [ ] My change requires a change to Fauna documentation.
----
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

Update Node environments

---

__tests__/integration/query.test.ts
src/errors.ts
src/wire-protocol.ts

[FE-6078](https://faunadb.atlassian.net/browse/FE-6078)
Update the `QueryStats` type to include the `rate_limits_hit` field, which is included in the response of throttling errors. 
There is no issue with JavaScript populating stats with the `rate_limits_hit` response, but it is inaccessible to TypeScript users relying on our types.
I extended a test that ensures the stats are propagated to query responses. Existing tests ensure that stats go to the right place for `ServiceErrors`. There are no existing integration tests that demonstrate stats actually come from the database, and none were added.
Here are some screenshots of me triggering rate limiting with the raw responses
_Read limit_
_Write limit_
_Compute limit_
`rate_limits_hit` is returned as an empty array on successful queries
* …

Add `rate_limits_hit` to `QueryStats` type

---

__tests__/functional/feed-client-configuration.test.ts
src/client.ts

This PR adds a validation check for cursor and makes sure it's a string at runtime. Non-string values can produce vague error messages otherwise.
This PR follows the current client configuration validation pattern to make sure `cursor` is a string when it is set.
While testing this change internally, we discovered if you managed to pass a non-string cursor during runtime, the error returned wasn't very helpful. It's probably easiest to mitigate this by validating it.
Added a test to the existing client configuration tests. The existing tests still pass.
* - [X] Bug fix (non-breaking change that fixes an issue)
* - [X] My code follows the code style of this …

Validate cursor for feeds

---

__tests__/integration/feed.test.ts
src/client.ts

This PR enables supplying a `cursor` value when using an unevaluated query with `client.feed()`.
This PR removes a check that prevented you from calling `client.feed()` with a `query` and a `cursor`. It is an unnecessary constraint, and event feeds will behave as you'd expect without this check.
This change allows you to resume at a given cursor while still passing in a query to generate the event source. Before this change, you'd need to first evaluate the query for the event source yourself before calling `feed` with `cursor`.
* An integration test on client was added
* Existing integration tests pass …

Allow using a query and cursor together when calling client.feed()

---

concourse/scripts/docker-compose-fauna.yml

This PR updates the concourse pipeline to use fauna/faunadb:latest. The current version does not have event feed support in it.
This updates the image from 5.10.0 to use latest.
The release pipeline should always run against the newest docker image for Fauna as that will represent the most up-to-date APIs and behaviors.
This PR will need to kick down the concourse pipeline.
* - [x] My code follows the code style of this project.
* - [ ] My change requires a change to Fauna documentation.

Use fauna/faunadb:latest in our release pipeline

---

concourse/pipeline.yml

Adds a missing step to the release pipeline for docs.
Without this step, we can't autogen + publish docs on release. 😢  See https://concourse.faunadb.net/teams/devex/pipelines/js-driver-release-v10/jobs/release/builds/42
```
fly validate-pipeline --config concourse/pipeline.yml
looks good
```
* - [ ] My code follows the code style of this project.
* - [ ] My change requires a change to Fauna documentation.
----
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …

Fix concourse pipeline for docs gen

---

src/client-configuration.ts

Documents accepted range for `page_size` in `FeedClientConfiguration`
Keeps docs updated with changes in https://github.com/fauna/core/pull/12010.
N/A
* - [ ] Bug fix (non-breaking change that fixes an issue)
* - [ ] My code follows the code style of this project.
* - [x] My change requires a change to Fauna documentation.
* - [x] My change requires a change to the README, and I have updated it accordingly.
----

[DOCS-3750] Event Feeds: Document `page_size` limit

---

__tests__/functional/client-configuration.test.ts
src/client-configuration.ts
src/client.ts
src/wire-protocol.ts
yarn.lock

ENG-6989
This allows the driver to be configured to query with performance hints enabled. When enabled, performance hints will be returned in the summary of the response. 
Without this change we won't be able to display performance hints in the dashboard or CLI. Performance hints are intended to be a self service way for users to debug query performance/cost and just overall find ways to improve their queries.
I added a test for the specified header. I also tested this version of the CLI with a locally running version of the dashboard to ensure I could get performance hints to show up.
* - [ ] Bug fix (non-breaking change that fixes an issue)
*  [ x ] New feature (non-breaking change that adds functionality)
* [ x ] My code …

Add performance hints support

---

__tests__/functional/client-configuration.test.ts
__tests__/functional/feed-client-configuration.test.ts
__tests__/functional/feed-client.test.ts
__tests__/functional/stream-client-configuration.test.ts
__tests__/integration/client-last-txn-tracking.test.ts
__tests__/integration/feed.test.ts
__tests__/integration/query.test.ts
__tests__/integration/set.test.ts
__tests__/integration/stream.test.ts
__tests__/unit/logger.test.ts
src/client-configuration.ts
src/client.ts
src/http-client/fetch-client.ts
src/http-client/http-client.ts
src/http-client/node-http2-client.ts
src/index.ts
src/util/logging.ts

util/logging.ts: Add LogHandler interface, LogLevel enum, and ConsoleLogHandler.
Add a log handler interface and implementation.
Following a LSE where we couldn't get reliable information from the customer side, we decided to add a logging facility to all of the drivers.
I spent a few hours surveying log library options in JavaScript/TypeScript. The conclusion that I came to is that they are either bulkier than what we need (log4js-node) or so simple that it's not worth us taking a dependency (pino), hence the strategy I adopted in this PR.
TODO: This PR does not yet actually call our log function from the request/response path, I thought the tests were failing on Monday. They appear to pass in GitHub Actions, so maybe that's a "fails on my machine" type of thing.
Unit tests?
* - [ ] Bug …

util/logging.ts: Add support for logging

---

__tests__/unit/query.test.ts
src/client.ts

https://faunadb.atlassian.net/browse/FE-6237
Core router may return a 200 with an empty response, indicating an issue on their end. [See LSE](https://faunadb.atlassian.net/browse/LSE-205)
Don't try to parse that like we do a normal response, instead throw a protocol error.
Added a query test
Shell before:
Shell after:

v10 driver - empty 200 response throws protocol error

---

__tests__/functional/client-configuration.test.ts
__tests__/functional/feed-client.test.ts
__tests__/integration/client-last-txn-tracking.test.ts
__tests__/integration/query.test.ts
__tests__/integration/set.test.ts
src/client.ts
src/http-client/fetch-client.ts
src/http-client/http-client.ts
src/http-client/node-http2-client.ts

This PR removed backwards-incompatible changes introduced in v2.4.0: remove the `getURL()` method from the `HTTPClient` interface.
Full (and accurate!) endpoints are not available at the point of logging for feeds and streams, so I updated the debug message to be the request path instead of full URL.
Bonus: 
- Added a debug line to starting stream connection for consistency with query and feed.
- tidied up imports
In #308, published in v2.4.0, we added some basic logging infrastructure, but that made breaking changes to the `HTTPClient` API. In retrospect, I don't believe those were helpful changes either - The `getURL()` implementations added to the built-in clients do not change with the request path, so using `getURL` when you want to gather information for a stream request, for …

Revert backwards incompatible changes to HTTPClient interface

---

overview.md

The modules link in the [driver reference docs](https://fauna.github.io/fauna-js/latest/) is broken. This fixes the link. I've manually fixed the link in our existing docs.
See above. 
Ran `npm run doc` and checked the link.
* - [ ] My code follows the code style of this project.
* - [x] My change requires a change to Fauna documentation.
----

Fix modules link in ref docs

---

README.md

We recently aligned with marketing to use sentence case for several feature names, including "event feed" and "event stream." This updates the README docs.
Better alignment with marketing and other docs
N/A
* - [ ] Bug fix (non-breaking change that fixes an issue)
* - [ ] My code follows the code style of this project.
* - [x] My change requires a change to Fauna documentation.
----

docs: README: Update several feature names to sentence case

---

concourse/scripts/publish_docs.sh

Our deployment workflows have a bug for docs publication.
They attempt to read files using incorrect relative paths.
This change uses the correct relative path; this should enable us to automate docs publishing again.
We would like to automate docs publishing.
The best way to test this is to run the automation.
N/A
* - [x] My code follows the code style of this project.
* - [ ] My change requires a change to Fauna documentation.
----
By submitting this pull request, I confirm that you can use, modify, copy, and …

Respect the relative path to the fauna-js-repository during doc publication.
